= JCR Unit

image:https://img.shields.io/maven-central/v/com.buralotech.oss.jcrunit/jcrunit[link=https://search.maven.org/search?q=g:%22com.buralotech.oss.jcrunit%22%20AND%20a:%22jcrunit%22] image:https://img.shields.io/github/license/bmatthews68/jcrunit[] image:https://img.shields.io/github/actions/workflow/status/bmatthews68/jcrunit/maven.yml[GitHub Actions Workflow Status] image:https://img.shields.io/librariesio/github/bmatthews68/jcrunit[Libraries.io dependency status for GitHub repo]


*JCR Unit* provides a https://github.com/junit-team/junit/wiki/Rules[JUnit 4 rule] and JUnit 5 extension for use when testing code that depends on a https://jcp.org/en/jsr/detail?id=283[Java Content Repository 2.0] implementation. It creates an in-memory content repository using the https://jackrabbit.apache.org/oak/[Jackrabbit Oak] implementation.

The current release only supports file (`nt:file`) and folder (`nt:folder`) node types.

== Requirements

[%autowidth,cols="h,a"]
|===
| 4.0.x
|
* Java 21
* JUnit 4.13.2
* JUnit Jupiter 5.11.4
| 4.1.x
|
* Java 25
* JUnit 4.13.2
* JUnit Jupiter 6.0.0
|===

== Usage

=== JUnit 4

[source,java]
----
class RepositoryTest {

    @Rule
    public JCRRepositoryRule repositoryRule = JCRRepositoryRule.withCredentials("root", "secret".toCharArray()); // <1>

    @Test
    public void checkSomething() {
        // ...
    }
}
----
<1> Create a rule and configure the username/password credentials.

=== JUnit 5

[source,java]
----
@ExtendWith(JCRRepositoryExtension.class) // <1>
@JCRRepositoryConfiguration(username = "root", password = {'s', 'e', 'c', 'r', 'e', 't'}) // <2>
class RepositoryTest {

    @Test
    void checkSomething(final JCRRepositoryTester helper) { // <3>
        // ...
    }
}
----
<1> Register the extension
<2> Configure repository with the username/password credentials
<3> Inject a freshly created `JCRRepositoryTestar`

== Maven Central Coordinates

**JCRUnit** has been published in [Maven Central](http://search.maven.org) at the following coordinates:

[source,xml]
----
<dependency>
    <groupId>com.buraolotech.oss.jcrunit</groupId>
    <artifactId>jcrunit</artifactId>
    <version>4.0.0</version>
</dependency>
----

== Credits

Internally *JCRUnit* is using the https://jackrabbit.apache.org/oak/[Jackrabbit Oak] to run the in-memory content repository.

== License & Source Code

The *JCRUnit* is made available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache License] and the source code is hosted on http://github.com[GitHub] at https://github.com/bmatthews68/jcrunit.
